CREATE TABLE "AspNetRoles"
(
    "Id"               TEXT        NOT NULL,
    "Discriminator"    VARCHAR(13) NOT NULL,
    "Name"             VARCHAR(256),
    "NormalizedName"   VARCHAR(256),
    "ConcurrencyStamp" TEXT,
    CONSTRAINT "PK_AspNetRoles"
        PRIMARY KEY ("Id")
);

ALTER TABLE "AspNetRoles"
    OWNER TO mimic_owner;

CREATE UNIQUE INDEX "RoleNameIndex"
    ON "AspNetRoles" ("NormalizedName");

INSERT INTO "AspNetRoles" ("Id", "Discriminator", "Name", "NormalizedName") 
VALUES ('667fbe5e-157e-4e86-bee2-e411c2d6ff10', 'UserRole', 'admin:read', 'ADMIN:READ'),
       ('667fbe5e-157e-4e86-bee2-e411c2d6ff11', 'UserRole', 'admin:write', 'ADMIN:WRITE');

CREATE TABLE "AspNetUsers"
(
    "Id"                   TEXT    NOT NULL,
    "UserName"             VARCHAR(256),
    "NormalizedUserName"   VARCHAR(256),
    "Email"                VARCHAR(256),
    "NormalizedEmail"      VARCHAR(256),
    "EmailConfirmed"       BOOLEAN NOT NULL,
    "PasswordHash"         TEXT,
    "SecurityStamp"        TEXT,
    "ConcurrencyStamp"     TEXT,
    "PhoneNumber"          TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled"     BOOLEAN NOT NULL,
    "LockoutEnd"           TIMESTAMP WITH TIME ZONE,
    "LockoutEnabled"       BOOLEAN NOT NULL,
    "AccessFailedCount"    INTEGER NOT NULL,
    CONSTRAINT "PK_AspNetUsers"
        PRIMARY KEY ("Id"),
    CONSTRAINT "Unique_Email"
        UNIQUE ("Email"),
    CONSTRAINT "Unique_Username"
        UNIQUE ("UserName")
);

ALTER TABLE "AspNetUsers"
    OWNER TO mimic_owner;

CREATE INDEX "EmailIndex"
    ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex"
    ON "AspNetUsers" ("NormalizedUserName");

CREATE TABLE "AspNetRoleClaims"
(
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "RoleId"     TEXT NOT NULL,
    "ClaimType"  TEXT,
    "ClaimValue" TEXT,
    CONSTRAINT "PK_AspNetRoleClaims"
        PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"
            ON DELETE CASCADE
);

ALTER TABLE "AspNetRoleClaims"
    OWNER TO mimic_owner;

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE "AspNetUserClaims"
(
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "UserId"     TEXT NOT NULL,
    "ClaimType"  TEXT,
    "ClaimValue" TEXT,
    CONSTRAINT "PK_AspNetUserClaims"
        PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"
            ON DELETE CASCADE
);

ALTER TABLE "AspNetUserClaims"
    OWNER TO mimic_owner;

CREATE INDEX "IX_AspNetUserClaims_UserId"
    ON "AspNetUserClaims" ("UserId");

CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider"       TEXT NOT NULL,
    "ProviderKey"         TEXT NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId"              TEXT NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins"
        PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"
            ON DELETE CASCADE
);

ALTER TABLE "AspNetUserLogins"
    OWNER TO mimic_owner;

CREATE INDEX "IX_AspNetUserLogins_UserId"
    ON "AspNetUserLogins" ("UserId");

CREATE TABLE "AspNetUserRoles"
(
    "UserId" TEXT NOT NULL,
    "RoleId" TEXT NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles"
        PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"
            ON DELETE CASCADE
);

ALTER TABLE "AspNetUserRoles"
    OWNER TO mimic_owner;

CREATE INDEX "IX_AspNetUserRoles_RoleId"
    ON "AspNetUserRoles" ("RoleId");

CREATE TABLE "AspNetUserTokens"
(
    "UserId"        TEXT NOT NULL,
    "LoginProvider" TEXT NOT NULL,
    "Name"          TEXT NOT NULL,
    "Value"         TEXT,
    CONSTRAINT "PK_AspNetUserTokens"
        PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"
            ON DELETE CASCADE
);

ALTER TABLE "AspNetUserTokens"
    OWNER TO mimic_owner;